package:
  name: recsys_slates_dataset
  version: 1.0.1
source:
  sha256: 4282b4bcd8cfc65741fd5b61e4a5f45d177a13b8e73f61e9ce8586f76d068740
  url: https://files.pythonhosted.org/packages/83/eb/a1c5d43f6da002ae32baf3374ba862d93917d154635457ccbe4a11d56a50/recsys_slates_dataset-1.0.1.tar.gz
about:
  dev_url: http://opensource.finn.no
  doc_url: http://opensource.finn.no
  home: http://opensource.finn.no
  license: Apache Software
  license_family: APACHE
  summary: Recommender Systems Dataset from FINN.no containing the presented items
    and whether and what the user clicked on.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - finn-no
requirements:
  host:
  - pip
  - python
  - packaging
  - requests>=2.25.1
  - numpy>=1.19.5
  - pandas>=1.0.5
  - torch>=1.9.0
  - PyYAML==5.4.1
  - googledrivedownloader>=0.4
  - pytorch-lightning>=1.4.1
  run:
  - pip
  - python
  - packaging
  - requests>=2.25.1
  - numpy>=1.19.5
  - pandas>=1.0.5
  - torch>=1.9.0
  - PyYAML==5.4.1
  - googledrivedownloader>=0.4
  - pytorch-lightning>=1.4.1
test:
  imports:
  - recsys_slates_dataset
